### ISSUE TITLE
there is no "component model"

### ISSUE THREAD

**Issue by joshski** [featurist/hyperdom#21]
...still appears near the end of README and seems odd after the explanation about components.

Plastiq does have a "component model" now, right?

**Comment by joshski** [comment]
Struggling to think of a better way to phrase this... maybe: "of course it helps to split views into reusable components, but they are represented as pure functions, not stateful objects"

**Comment by refractalize** [comment]
yeah i think that whole section can be rephrased. it's useful, because it describes some things about how plastiq apps are structured, but the components bit probably isn't necessary.

**Comment by refractalize** [comment]
fixed in new docs
