### ISSUE TITLE
catch for all event handlers that return promises?

### ISSUE THREAD

**Issue by joshski** [featurist/hyperdom#56]
I wondered whether it might be handy to include a mechanism for giving plastiq a catch block for unhandled rejection of promises returned by event handlers. There's an argument that we already have a global way of doing this (`window.addEventListener('unhandledrejection', ...`) but it doesn't work very well, or in a non-window environment. Or do you think this is userland responsibility?

**Comment by refractalize** [comment]
I'm thinking this belongs in userland... Node is pretty aware of unhandled rejections now, and so are most browsers. Closing
