### ISSUE TITLE
hyperdom.html("a.z") makes <a.z> not <a class="z">

### ISSUE THREAD

**Issue by joshski** [featurist/hyperdom#60]
I think this is a regression, i.e. an old `plastiq.html("a.z")` would have created `<a class="z">`

https://github.com/joshski/bloom-editor/commit/2a891ebcd8e2474abfddb7755d0c074627451f26

**Comment by refractalize** [comment]
I've not been able to reproduce this and there are automated tests on all browsers that show that it works. Can you isolate this any further?

**Comment by joshski** [comment]
Nah, can't reproduce it now
