### ISSUE TITLE
hyperx

### ISSUE THREAD

**Issue by dereke** [featurist/hyperdom#68]
it would be cool if hyperdom had integration with [hyperx](https://github.com/substack/hyperx) so you could do something like this:

```
var hx = require('hyperdom/hx')
```

**Comment by refractalize** [comment]
i'm not 100% sure, just because we need to keep hyperdom up to date with the latest hyperx releases, or peer dependency..? But to be honest, this is not hard to do:

```js
var hx = require('hyperx')(require('hyperdom').jsx)
```

perhaps we just need some docs for it?

**Comment by dereke** [comment]
I was thinking just having hyperx as a runtime dependency so it wouldn't even exist in hyperdom/package.json

then in hyperdom wrap it in a try catch and throw an error saying you need to install hyperx to use this - just like we do in sworm.

I guess it would be this simple:

```js
try {
  module.exports = require('hyperx')(require('hyperdom').jsx)
}
catch {
  throw new Error('to use hyperx with hyperdom you need to install the hyperx package') 
}
```

**Comment by refractalize** [comment]
Ok sounds good!
Derek Ekins <notifications@github.com> schrieb am Mo. 20. März 2017 um
08:49:

**Comment by joshski** [comment]
👍🏻

**Comment by joshski** [comment]
Is there some runtime performance penalty for hyperx? Or any way to rewrite hyperx into function calls like we do with jsx?

**Comment by dereke** [comment]
Yes you can hyperxify it of course :-)
https://www.npmjs.com/package/hyperxify

**Comment by dereke** [comment]
see #73 for implementation
