### ISSUE TITLE
route.isActive not working in some cases?

### ISSUE THREAD

**Issue by artemave** [featurist/hyperdom#82]
I have `home = router.route('/')` and a "Home" tab that is active when `home.isActive()`. It works like this:

![image](https://cloud.githubusercontent.com/assets/23721/25964702/a6889364-367d-11e7-81fc-bb0effe6019c.png)

However, I was also expecting it'd keep the tab active when there are query string params in the url. However:

![image](https://cloud.githubusercontent.com/assets/23721/25964939/6b6b42d0-367e-11e7-848b-95f0a14ddc87.png)

**Comment by refractalize** [comment]
cheers @artemave - fixed in 094eb80
